-- -----------------------------------------------------------------------------
-- Tables
-- -----------------------------------------------------------------------------

-- Table to store service jids
create table tig_pubsub_service_jids (
	service_id bigint generated by default as identity not null,
	service_jid varchar(2049) not null,
	
	primary key ( service_id )
);

create unique index tig_pubsub_service_jids_service_jid on tig_pubsub_service_jids ( service_jid );

-- Table to store jids of node owners, subscribers and affiliates
create table tig_pubsub_jids (
	jid_id bigint generated by default as identity not null,
	jid varchar(2049) not null,

	primary key ( jid_id )
);

create unique index tig_pubsub_jids_jid on tig_pubsub_jids ( jid );

-- Table to store nodes configuration
create table tig_pubsub_nodes (
	node_id bigint generated by default as identity not null,
	service_id bigint not null references tig_pubsub_service_jids ( service_id ),
	name varchar(1024) not null,
	type int not null,
	title varchar(1000),
	description varchar(32672),
	creator_id bigint references tig_pubsub_jids ( jid_id ),
	creation_date timestamp,
	configuration varchar(32672),
	collection_id bigint references tig_pubsub_nodes ( node_id ),
	
	primary key ( node_id )
);

create index tig_pubsub_nodes_service_id on tig_pubsub_nodes ( service_id );
create index tig_pubsub_nodes_name on tig_pubsub_nodes ( name );
create unique index tig_pubsub_nodes_service_id_name on tig_pubsub_nodes ( service_id, name );
create index tig_pubsub_nodes_collection_id on tig_pubsub_nodes ( collection_id );

-- Table to store user nodes affiliations
create table tig_pubsub_affiliations (
	node_id bigint not null references tig_pubsub_nodes ( node_id ),
	jid_id bigint not null references tig_pubsub_jids ( jid_id ),
	affiliation varchar(20) not null,

	primary key ( node_id, jid_id )
);

create index tig_pubsub_affiliations_node_id on tig_pubsub_affiliations ( node_id );
create index tig_pubsub_affiliations_jid_id on tig_pubsub_affiliations ( jid_id );

-- Table to store user nodes subscriptions
create table tig_pubsub_subscriptions (
	node_id bigint not null references tig_pubsub_nodes ( node_id ),
	jid_id bigint not null references tig_pubsub_jids ( jid_id ),
	subscription varchar(20) not null,
	subscription_id varchar(40) not null,

	primary key ( node_id, jid_id )
);

create index tig_pubsub_subscriptions_node_id on tig_pubsub_subscriptions ( node_id );
create index tig_pubsub_subscriptions_jid_id on tig_pubsub_jids ( jid_id );

-- Table to store items
create table tig_pubsub_items (
	node_id bigint not null references tig_pubsub_nodes ( node_id ),
	id varchar(1024) not null,
	creation_date timestamp,
	publisher_id bigint references tig_pubsub_jids ( jid_id ),
	update_date timestamp,
	data varchar(32672),

	primary key ( node_id, id )
);

create index tig_pubsub_items_node_id on tig_pubsub_items ( node_id );
create index tig_pubsub_items_id on tig_pubsub_items ( id );

-- -----------------------------------------------------------------------------
-- Functions
-- -----------------------------------------------------------------------------
create procedure TigPubSubCreateNode(service_jid varchar(2049), node_name varchar(1024),
	node_type int, node_creator varchar(2049), node_conf varchar(32672), collection_id bigint)
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubCreateNode';


create or replace function TigPubSubRemoveNode(node_id bigint)
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubRemoveNode';

create procedure TigPubSubGetItem(node_id bigint, item_id varchar(1024))
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubGetItem';


create procedure TigPubSubWriteItem(node_id bigint, item_id varchar(1024),
	publisher varchar(2049), item_data varchar(32762))
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubWriteItem';

create procedure TigPubSubDeleteItem(node_id bigint, item_id varchar(1024))
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubDeleteItem';

create procedure TigPubSubGetNodeId(service_jid varchar(2049), node_name varchar(1024))
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubGetNodeId';

create procedure TigPubSubGetNodeItemsIds(node_id bigint)
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubGetNodeItemIds';

create procedure TigPubSubGetNodeItemsIdsSince(node_id bigint, since timestamp)
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubGetNodeItemIdsSince';

create procedure TigPubSubGetAllNodes(service_jid varchar(2049))
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubGetAllNodes';

create procedure TigPubSubGetRootNodes(service_jid varchar(2049))
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubGetRootNodes';

create procedure TigPubSubGetChildNodes(service_jid varchar(2049), node_name varchar(1024))
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubGetChildNodes';

create procedure TigPubSubDeleteAllNodes(service_jid varchar(2049))
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubDeleteAllNodes';

create procedure TigPubSubSetNodeConfiguration(node_id bigint, node_conf text, collection_id bigint)
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubSetNodeConfiguration';

create procedure TigPubSubSetNodeAffiliation(node_id bigint, jid varchar(2049), affil varchar(20))
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubSetNodeAffiliation';

create procedure TigPubSubGetNodeConfiguration(node_id bigint)
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubGetNodeConfiguration';

create procedure TigPubSubGetNodeAffiliations(node_id bigint)
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubGetNodeAffiliations';

create procedure TigPubSubGetNodeSubscriptions(node_id bigint)
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubGetNodeSubscriptions';

create procedure TigPubSubSetNodeSubscription(node_id bigint, jid varchar(2049), subscr varchar(20),
	subscr_id varchar(40))
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubSetNodeSubscription';

create procedure TigPubSubDeleteNodeSubscription(node_id bigint, jid varchar(2049))
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubDeleteNodeSubscription';

create procedure TigPubSubGetUserAffiliations(service_jid varchar(2049), jid varchar(2049)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubGetUserAffiliations';

create procedure TigPubSubGetUserSubscriptions(service_jid varchar(2049), jid varchar(2049)) 
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubGetUserSubscriptions';

create procedure TigPubSubGetNodeItemsMeta(node_id bigint)
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	READS SQL DATA
	DYNAMIC RESULT SETS 1
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubGetNodeItemsMeta';

create procedure TigPubSubFixNode(node_id bigint, creation_date timestamp)
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubFixNode';

create procedure TigPubSubFixItem(node_id bigint, item_id varchar(1024),
	creation_date timestamp, update_date timestamp)
	PARAMETER STYLE JAVA
	LANGUAGE JAVA
	MODIFIES SQL DATA
	EXTERNAL NAME 'tigase.pubsub.repository.derby.StoredProcedures.tigPubSubFixItem';

